[package]
name = "tile-game"
version = "0.1.0"
edition = "2021"
resolver = "2"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sixtyfps = "0.1.4"
rand = "0.8"

[build-dependencies]
sixtyfps-build = "0.1.4"
